// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using newwebapi.Models;

namespace Companies.Migrations
{
    [DbContext(typeof(CompanyContext))]
    [Migration("20200228061626_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("newwebapi.Models.Company", b =>
                {
                    b.Property<string>("CompanyName")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("number");

                    b.HasKey("CompanyName");

                    b.ToTable("CompanyNames");
                });
#pragma warning restore 612, 618
        }
    }
}
